apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: madworld-ingress
  namespace: madworld
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: api.mad-world.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: madworld-api-loadbalancer
                port:
                  number: 80
---
  tls:
    - hosts:
        - api.mad-world.nl
      secretName: madworld-letsencrypt-prod-key
      apiVersion: cert-manager.io/v1
      kind: Issuer
      metadata:
        name: letsencrypt-prod
        namespace: madworld
      spec:
        acme:
          # Staging API
          server: https://acme-staging-v02.api.letsencrypt.org/directory
          email: oveldman@gmail.com
          privateKeySecretRef:
            name: madworld-letsencrypt-prod-key
          solvers:
            - http01:
                ingress:
                  class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: madworld-letsencrypt-prod
  namespace: madworld
spec:
  secretName: madworld-letsencrypt-prod-key
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
    - api.mad-world.nl
      