apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    email:  oveldman@gmail.com # Change the email here
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-prod
    solvers:
      - http01:
          ingress:
            class: public
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: madworld-ingress
  namespace: madworld
spec:
  rules:
    - host: api.mad-world.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: madworld-api-loadbalancer
                port:
                  number: 80
    - host: www.mad-world.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: madworld-ui-loadbalancer
                port:
                  number: 80